spring:
  application:
    name: Sparkle3
  web:
    resources:
      static-locations: "classpath:/static/,file:./static/"
  threads:
    virtual:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://local:5432/sparkle
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6372
      client-name: sparkle-redis
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client
            client-secret: clientsecret
            authorization-grant-type: authorization_code
            # /login/oauth2/code/ 固定格式
            redirect-uri: "http://localhost:7799/login/oauth2/code/github"
            # GitHub 的权限范围
            scope:
              - read:user
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
server:
  address: 0.0.0.0
  port: 7799
  compression:
    enabled: true
  tomcat:
    remoteip:
      host-header: X-Forwarded-For
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: "deleted_at"
      logic-delete-value: "now()"
      logic-not-delete-value: null
sparkle:
  root-url: "http://127.0.0.1:7799"
  captcha:
    pow:
      endpoint: "${sparkle.root-url}/ping/captcha/createSession"
      difficulty-bits: 5
      algorithm: SHA-256
  ping:
    config:
      min-protocol-version: 20
      max-protocol-version: 20
    sync-banhistory:
      pow-captcha: false
      endpoint: "${sparkle.root-url}/ping/syncBanHistory"
      random-initial-delay: 3000
      interval: 10000
    sync-swarm:
      pow-captcha: false
      endpoint: "${sparkle.root-url}/ping/syncSwarm"
      random-initial-delay: 3000
      interval: 10000
      cleanup-before: 2592000000
      cleanup-cron: "0 0 0 * * *"
    rule-ip-denylist:
      pow-captcha: false
      endpoint: "${sparkle.root-url}/ping/ruleIpDenylist"
      random-initial-delay: 3000
      interval: 10000
    rule-peer-identity:
      pow-captcha: false
      endpoint: "${sparkle.root-url}/ping/rulePeerIdentity"
      random-initial-delay: 3000
      interval: 10000
    reconfigure:
      random-initial-delay: 600000
      interval: 10800000
    heartbeat:
      pow-captcha: true
      endpoint: "${sparkle.root-url}/ping/heartbeat"
      random-initial-delay: 3000
      interval: 10000
      multi-if: true
      cleanup-before: 2592000000
      cleanup-cron: "0 0 0 * * *"
    query-ip:
      pow-captcha: true
      endpoint: "${sparkle.root-url}/ping/queryIp"
      iframe-endpoint: "${sparkle.root-url}/ping/queryIp/widget"
  analyse:
    untrusted-vote:
      schedule: "0 0 * * * *"
      duration: 1209600000
      ipv4:
        enable: true
        min-userapps-vote: 3
        min-ban-count: 5
      ipv6:
        enable: true
        min-userapps-vote: 3
        min-ban-count: 5
    overdownload-analyse:
      schedule: "0 0 * * * *"
      duration: 1209600000
      threshold: 3.2
    concurrent-download-analyse:
      schedule: "0 0 * * * *"
      duration: 3600000
      threshold-concurrent: 150
      threshold-userapps: 3
  query:
    query-ip:
      include-modules: "com.ghostchu.peerbanhelper.module.impl.rule.ProgressCheatBlocker,com.ghostchu.peerbanhelper.module.impl.rule.MultiDialingBlocker,com.ghostchu.peerbanhelper.module.impl.rule.AutoRangeBan"
      bans-counting-duration: 604800000
      swarms-counting-duration: 604800000
      traffic-measure-duration: 604800000
      torrents-counting-duration: 604800000
      heartbeat-query-duration: 604800000
  github-sync:
    schedule: "0 /30 * * * *"
    personal-access-token: sometoken
    org-name: PBH-BTN
    repository-name: BTN-Collected-Rules-BTN3
    branch-name: master
